name: Docker
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  IMAGE_NAME: docker-php-base-image

jobs:
  test-multiarch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          [
            8-1-10,
            8-1-5,
            8-0-8,
            7-4-30,
            7-4-29,
            7-4-26,
            7-4-20,
            7-4-16,
            7-4-6,
            7-3-24,
          ]
        flavour: ["", "-rootless"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and test the image
        run: make build-${{ matrix.tag }}${{ matrix.flavour }}

  deploy-multiarch:
    needs: test-multiarch
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        tag:
          [
            7.3.24-fpm-alpine3.12,
            7.4.6-fpm-alpine3.10,
            7.4.16-fpm-alpine3.13,
            7.4.20-fpm-alpine3.13,
            7.4.26-fpm-alpine3.15,
            7.4.29-fpm-alpine3.15,
            7.4.30-fpm-alpine3.16,
            8.0.8-fpm-alpine3.13,
            8.1.5-fpm-alpine3.15,
            8.1.10-fpm-alpine3.16,
          ]
        flavour: ["", "-rootless"]
    steps:
      - uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Check directory and Dockerfile
        run: |
          # Guess the folder for the php configuration
          BASE_FOLDER=$(./scripts/guess_folder.sh "${{ matrix.tag }}")
          if [ ! -d "$BASE_FOLDER" ]; then
            echo "Fail to guess the configuration folder"
            exit 1
          fi

          test -d $BASE_FOLDER && test -f $BASE_FOLDER/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push images to GitHub Container Registry
        if: ${{ matrix.flavour == '' }}
        run: |
          # Guess the folder for the php configuration
          BASE_FOLDER=$(./scripts/guess_folder.sh "${{ matrix.tag }}")
          if [ ! -d "$BASE_FOLDER" ]; then
            echo "Fail to guess the configuration folder"
            exit 1
          fi

          # Build process
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          docker buildx build --push $BASE_FOLDER --platform "linux/amd64,linux/arm64" --build-arg PHPVER=${{ matrix.tag }} --tag $IMAGE_ID:${{ matrix.tag }}

      - name: Build and push images to GitHub Container Registry (rootless)
        if: ${{ matrix.flavour == '-rootless' }}
        run: |
          # Guess the folder for the php configuration
          BASE_FOLDER=$(./scripts/guess_folder.sh "${{ matrix.tag }}")
          if [ ! -d "$BASE_FOLDER" ]; then
            echo "Fail to guess the configuration folder"
            exit 1
          fi

          # Build process
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          docker buildx build --push $BASE_FOLDER --platform "linux/amd64,linux/arm64" --build-arg PHPVER=${{ matrix.tag }} --build-arg user=1001 --tag $IMAGE_ID:${{ matrix.tag }}-rootless
