name: QA
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  check-shell-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
